trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'subscription-id'
  # Web app name
  webAppName: 'web-app-name'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'environment-name'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  variables:
    phpVersion: '8.3'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    #- script: |
    #    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    #    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    #    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    #    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    #    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    #    php -version
    #  workingDirectory: $(rootFolder)
    #  displayName: 'Use PHP version $(phpVersion)'

    #- script: composer install --no-interaction --prefer-dist
    #  workingDirectory: $(rootFolder)
    #  displayName: 'Composer install dans le repertoire : $(rootFolder)'
    
    - script: |
        echo $(RQEXTENSIONS)
        cat $(rootFolder)/composer.json
        echo "one potato two potato" | awk '{gsub(/potato/,"banana")}1'
        echo "one potato two potato" | awk '{sub(/potato/,"banana")}1'
        echo '========= Debut de explode============'
        IFS=';' read -ra extensions <<< "$(RQEXTENSIONS)"
        for extensionVersion in "${extensions[@]}"; 
        do
          echo "$extensionVersion"
          IFS=':' read -r -a extension <<< "$extensionVersion"
          echo "EXTENSION NOM ':' ${extension[0]}"
          echo "EXTENSION VERSION ':' ${extension[1]}"
          sed -i 's/devman\/${extension[0]}.*/devman\/${extension[0]}:"${extension[1]}"/g' $(rootFolder)/composer.json
        done
        echo '========= FIN de explode============'
        #sed -i 's/nesbot\/carbon.*/revenuquebec\/$(RQEXTENSIONS)/g' $(rootFolder)/composer.json
        echo "Apres remplacement"
        cat $(rootFolder)/composer.json
      displayName: Contenu du fichier composer